### ISSUE TITLE
Slides 6-7 of 1st lesson presentation incorrectly rendered

### ISSUE THREAD

**Issue by b8tt8** [nimbella/nimbella-training#1]
https://github.com/nimbella/nimbella-training/blob/master/1-nimcli/pres.pdf has slides 6-7 incorrectly rendered

![immagine](https://user-images.githubusercontent.com/6408826/104568569-8abdd080-5650-11eb-83b0-9f2e199df034.png)

**Comment by rabbah** [comment]
Thank you for the heads up @b8tt8.

**Comment by sciabarracom** [comment]
fixed
