### ISSUE TITLE
Command action:remove not found

### ISSUE THREAD

**Issue by Magicianred** [nimbella/nimbella-training#2]
Hi,

I found some typos in slide:
https://github.com/nimbella/nimbella-training/blob/master/1-nimcli/pres.pdf 

- page 25
say to digit command "nim action remove greetings -r" and I obtain "Error: command action:remove not found"

I see with the command "nim action -help" that the command is "action:delete"

- page 27
missing package and action name in the command

Thanks

**Comment by rabbah** [comment]
Thanks @Magicianred!

**Comment by sciabarracom** [comment]
Fixed
